name: Deploy Flutter Web to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Set up Flutter with updated version
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # Updated as suggested in the error
          channel: 'stable'
          cache: true
          
      # Change to the flutter_web directory
      - name: Change to flutter_web directory
        run: cd flutter_web
        
      # Install dependencies in the flutter_web directory
      - name: Install dependencies
        working-directory: ./flutter_web
        run: flutter pub get
        
      # Build the web app in the flutter_web directory
      - name: Build Flutter web
        working-directory: ./flutter_web
        run: flutter build web --release
        
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./flutter_web/build/web
          publish_branch: gh-pages
          keep_files: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'